<a href="https://colab.research.google.com/github/maribarbalho/CursoDeExtensaoPythonPandas/blob/main/Primeiro_Exemplo_em_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Primeiro exemplo de manipulação de dados usando Python Pandas.**


Autora: Mariana Barbalho

Data: 06/02/2023

In [1]:
# Importando biblioteca pandas no Python
import pandas as pd

combustiveis_df = pd.read_excel("ca-2021-02.xlsx")

In [2]:
# Usa o print para ver o dataframe!
print(combustiveis_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [3]:
# Uma forma para ver a base
display(combustiveis_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

In [4]:
# Exibe as 5 primeiras linhas
display(combustiveis_df.head())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA

In [5]:
# Para exibir as primeiras 15 linhas
display(combustiveis_df.head(15))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
11,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.987,NaN,R$ / litro,BRANCA
12,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.978,NaN,R$ / litro,BRANCA
13,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.989,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA

In [6]:
# Comandos Dataframe.shape() e DataFrame.describe() | Shape: mostra linhas e colunas | Describe
print(combustiveis_df.shape)

# Para mostrar somente as linhas:
print(combustiveis_df.shape[0])

(168409, 16)
168409

In [7]:
# Comandos Dataframe.shape() e DataFrame.describe() | Shape: mostra linhas e colunas | Describe: mostra estatísticas "mais básicas" que precisamos e é um metodo usado para resumo estatístico da distribuição de cada coluna numérica,  incluindo contagem, média, desvio padrão, valor minimo, quartis e valor maximo. 
# e se tiver colunas não numericas elas são ignoradas 


print(combustiveis_df.describe())

       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [8]:
# Quais são as colunas e que tipo de dados elas tem.
print(combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [9]:
# Filtrar apenas por uma coluna
display(combustiveis_df['Revenda'])

0                               POSTO ARAPIRACA LTDA
1                               POSTO ARAPIRACA LTDA
2                               POSTO ARAPIRACA LTDA
3                               POSTO ARAPIRACA LTDA
4                               POSTO ARAPIRACA LTDA
                             ...
168404    COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405             ABC DISTRIBUICAO DE PETROLEO LTDA
168406             ABC DISTRIBUICAO DE PETROLEO LTDA
168407             ABC DISTRIBUICAO DE PETROLEO LTDA
168408             ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, Length: 168409, dtype: object

In [10]:
 # Aqui criamos um dataframe apenas com as colunas desejadas
 ca_df = combustiveis_df[['Produto', 'Revenda', 'Municipio', 'Valor de Venda']]
 display(ca_df)

,Produto,Revenda,Municipio,Valor de Venda
0,GASOLINA,POSTO ARAPIRACA LTDA,ARAPIRACA,6.799
1,ETANOL,POSTO ARAPIRACA LTDA,ARAPIRACA,5.299
2,DIESEL,POSTO ARAPIRACA LTDA,ARAPIRACA,5.549
3,GASOLINA ADITIVADA,POSTO ARAPIRACA LTDA,ARAPIRACA,6.899
4,DIESEL S10,POSTO ARAPIRACA LTDA,ARAPIRACA,5.649
...,...,...,...,...
168404,ETANOL,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,5.859
168405,GASOLINA,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,6.580
168406,ETANOL,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,4.740
168407,DIESEL S10,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,5.448
168408,GASOLINA ADITIVADA,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,6.580

In [11]:
# Exibe a 4º Linha
display(ca_df.loc[3])

Produto             GASOLINA ADITIVADA
Revenda           POSTO ARAPIRACA LTDA
Municipio                    ARAPIRACA
Valor de Venda                   6.899
Name: 3, dtype: object

In [12]:
# Exibir da 10º linha até a 20º linha
display(ca_df.loc[9:19])

,Produto,Revenda,Municipio,Valor de Venda
9,DIESEL S10,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,5.983
10,GASOLINA,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,7.197
11,ETANOL,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,5.987
12,DIESEL,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,5.978
13,DIESEL S10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,5.989
14,GASOLINA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,7.175
15,ETANOL,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,5.930
16,DIESEL,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,5.955
17,GASOLINA ADITIVADA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,7.175
18,DIESEL S10,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,5.980
19,GASOLINA,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,6.990

In [13]:
# Criar dataframe gas_df contendo apenas as 4 colunas (Revenda, Municipio, Produto, Valor de Venda)
# gas_df = combustiveis_df[['Produto', 'Revenda', 'Municipio', 'Valor de Venda']]
gas_df = ca_df.loc[ca_df['Produto'] == 'GASOLINA']
display(gas_df)

display(gas_df['Valor de Venda'].max())

,Produto,Revenda,Municipio,Valor de Venda
0,GASOLINA,POSTO ARAPIRACA LTDA,ARAPIRACA,6.799
5,GASOLINA,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,7.198
10,GASOLINA,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,7.197
14,GASOLINA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,7.175
19,GASOLINA,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,6.990
...,...,...,...,...
168392,GASOLINA,AUTO POSTO KM BAURU LTDA,BAURU,6.199
168394,GASOLINA,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,ITUIUTABA,6.899
168399,GASOLINA,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,CAMPOS DOS GOYTACAZES,7.090
168403,GASOLINA,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,6.799
168405,GASOLINA,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,6.580

7.999

In [14]:
#Para saber qual posto e município da gasolina mais cara
display(gas_df[['Revenda', 'Municipio', 'Valor de Venda']].max())

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Valor de Venda                        7.999
dtype: object

In [15]:
#DataFrame.loc[] com múltiplas condições para filtragem
#Quais são so preços do ETANOL na minha cidade
etanol_barueri_df = ca_df.loc[(ca_df['Produto'] == 'ETANOL') & (ca_df['Municipio'] == 'BARUERI')]
etanol_barueri_df.sort_values(by="Valor de Venda")
display(etanol_barueri_df)

,Produto,Revenda,Municipio,Valor de Venda
17011,ETANOL,BETHAVILLE AUTO POSTO LTDA.,BARUERI,5.399
17014,ETANOL,AUTO POSTO DUQUE BARUERI LTDA.,BARUERI,5.399
17019,ETANOL,AUTO POSTO TRAPEZYUN LTDA,BARUERI,5.099
17022,ETANOL,AUTO POSTO LEAO DA ALDEIA LTDA,BARUERI,5.260
17025,ETANOL,CENTRO AUTOMOTIVO CRS LTDA,BARUERI,5.299
...,...,...,...,...
164846,ETANOL,POSTO DE SERVICO LUA NOVA LTDA,BARUERI,4.899
165045,ETANOL,AUTO POSTO DUQUE CONDE ALPHAVILLE LTDA,BARUERI,5.299
165839,ETANOL,AUTO POSTO NOVA UNIÃO LTDA,BARUERI,4.799
166260,ETANOL,POSTO PALACE ARAGUAIA LTDA,BARUERI,4.899
166420,ETANOL,AUTOPOSTO MACKENZIE LTDA,BARUERI,5.199

In [16]:
# Qual a média de preços dos combustíveis GASOLINA e GASOLINA ADITIVADA do Bairro MOOCA em SÃO PAULO?
display(combustiveis_df.loc[(combustiveis_df['Bairro'] == 'MOOCA') & 
                            (combustiveis_df['Municipio'] == 'SAO PAULO') & 
                            (combustiveis_df['Produto'].isin(["GASOLINA", "GASOLINA ADITIVADA"])), 
                            ['Valor de Venda']].mean())

Valor de Venda    6.575596
dtype: float64

In [17]:
# Como mostrar média de valor de venda POR COMBUSTÍVEL Brasil todo?
media_por_combustivel_df = ca_df[['Produto', 'Valor de Venda']].groupby(by='Produto').mean().round(2)
display(media_por_combustivel_df)

                    Valor de Venda
Produto
DIESEL                        5.38
DIESEL S10                    5.45
ETANOL                        5.46
GASOLINA                      6.71
GASOLINA ADITIVADA            6.86
GNV                           4.39

In [18]:
# Quero adicionar uma coluna de valor booleano no combustiveis_df 
# Chamada "Ativo" que, por padrão, vai ser True para 
# TODAS as linhas
combustiveis_df['Ativo'] = True
print(combustiveis_df.info())
display(combustiveis_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB
None

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True

In [21]:
# Exportar para Excel o dataframe com etanol em Indaiatuba....
etanol_barueri_df.to_excel('etanol_indaiatuba.xlsx', sheet_name='Etanol em Indaiatuba')